services:
  marriage_loan_bot:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "5900:5900"
    volumes:
      - ./:/app
    shm_size: '2g'
    user: root
    environment:
      - SE_VNC_PASSWORD=YourPassWord
